### ISSUE TITLE
怎么进行多个simple任务配置？

### ISSUE THREAD

**Issue by zjh8977** [xjzrc/elastic-job-spring-boot-starter#2]

**Comment by xjzrc** [comment]
@zjh8977 配置如下：
```yaml
spring:
  elasticjob:
    #注册中心配置
    zookeeper:
      server-lists: 127.0.0.1:6181
      namespace: elastic-job-spring-boot-stater-demo
    #简单作业配置
    simples:
      #spring简单作业示例配置
      spring-simple-job-01:
        #配置简单作业，必须实现com.dangdang.ddframe.job.api.simple.SimpleJob01
        job-class: com.zen.spring.boot.demo.elasticjob.job.SpringSimpleJob01
        cron: 0/2 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
      #spring简单作业示例配置
      spring-simple-job-02:
        #配置简单作业，必须实现com.dangdang.ddframe.job.api.simple.SimpleJob02
        job-class: com.zen.spring.boot.demo.elasticjob.job.SpringSimpleJob02
        cron: 0/2 * * * * ?
        sharding-total-count: 3
        sharding-item-parameters: 0=Beijing,1=Shanghai,2=Guangzhou
...
```
